from enum import StrEnum


class AuthReason(StrEnum):
    UNKNOWN = "UNKNOWN"
    NO_SUCH_APPLICATION = "NO_SUCH_APPLICATION"
    NO_MATCHING_RULE = "NO_MATCHING_RULE"
    TOKEN_EXPIRED = "TOKEN_EXPIRED"  # noqa: S105
    JWT_GLOBAL_ACCESS_CLAIM = "JWT_GLOBAL_ACCESS_CLAIM"
    JWT_CLAIM_MATCHES_APP = "JWT_CLAIM_MATCHES_APP"
    ACL_MATCHING_EMAIL = "ACL_MATCHING_EMAIL"
    ACL_MATCHING_DOMAIN = "ACL_MATCHING_DOMAIN"
    ACL_GLOBAL_ACCESS_EMAIL = "ACL_GLOBAL_ACCESS_EMAIL"
    ACL_GLOBAL_ACCESS_DOMAIN = "ACL_GLOBAL_ACCESS_DOMAIN"
