name: Release to PyPI

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v4

    - name: Set up Python
      run: uv python install 3.11

    - name: Install dependencies
      run: uv sync

    - name: Build package
      run: uv build

    - name: Publish to test PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      if: github.event.release.prerelease == true
      with:
        repository-url: 'https://test.pypi.org/legacy/'

    - name: Publish to prod PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      if: github.event.release.prerelease == false
