name: Publish python package

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: release
    permissions:
        id-token: write
        contents: read
    steps:
    - name: Validate semantic version
      uses: matt-usurp/validate-semver@7bbc9584679de1aeef57aa531504ab00438481ab
      with:
        version: 0.0.1-prerelease+logging01

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
          fetch-depth: 0

    - name: Install uv
      uses: astral-sh/setup-uv@v4

    - name: Install dependencies
      run: uv sync

    - name: Build
      run: uv build

    - name: Set release version
      run: uv version 0.0.1-prerelease+logging01

    - name: Publish to test pypi
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: 'https://test.pypi.org/legacy/'

